# Generated by Django 5.1.4 on 2024-12-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(default='user.png', upload_to='profile/', verbose_name='Profile Image'),
        ),
    ]
