# Generated by Django 5.1.4 on 2024-12-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Excerpt'),
        ),
    ]
